
FROM python:3.11-slim


ENV PYTHONUNBUFFERED=1


WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt || true


CMD ["sleep", "infinity"]
